language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
before_install:
  - "pip install -U pip"
  - "python setup.py install"
script:
    - "nosetests --with-coverage --cover-package app"
deploy:
  provider: heroku
  api_key:
    secure: "47d84d5a-d523-4b44-9165-cfe5c99d5ba7"
